#
# Base definition of the service. Reused in all docker-compose configs
#
version: "2"
services:
  service:
    build: .
    image: allaboutapps/aaa_backend_demo_image
    ports:
      - "8080:8080"
    # environment: # deactivated, env is used by default

  postgres:
    image: postgres:9.4
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=TbpT5EMJYm
      - POSTGRES_DB=aaa-backend-demo-db

  postgres-test:
    image: postgres:9.4
    command: postgres -c config_file=/etc/postgresql.conf
    volumes:
      - ./docker/postgres_test/postgresql.conf:/etc/postgresql.conf
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=TbpT5EMJYm
      - POSTGRES_DB=aaa-backend-demo-test-db
